import icon_compliance from './images/icon_compliance.png';
import icon_checklist from './images/icon_checklist.png';
import icon_event from './images/icon_event.png';
import icon_team from './images/icon_team.png';

function generateAProposContent() {
    const center = document.createElement('div');
        center.classList = "center";
        const title = document.createElement('div');
            title.classList = "center_title";
            title.innerHTML = 'Comment Kanply vous aidera&nbsp;?';
        center.appendChild(title);
        const itemContainer = document.createElement('div');
            itemContainer.classList = "center_items";
            const itemCompliance = document.createElement('div');
                itemCompliance.classList = 'center_item';
                const itemComplianceImageContainer = document.createElement('div');
                    itemComplianceImageContainer.classList = 'image';
                    const iconComplianceImage = new Image();
                        iconComplianceImage.src = icon_compliance;
                        iconComplianceImage.alt = "Compliance Icon";
                        iconComplianceImage.classList = "logo";
                    itemComplianceImageContainer.appendChild(iconComplianceImage);
                const itemComplianceDesc = document.createElement('div');
                    itemComplianceDesc.classList = 'subtext';
                    itemComplianceDesc.innerHTML = "Kanply établiera d'abord la liste de vos obligations légales et règlementaires.  Il vous aidera également à formuler les objectifs en matière de sécurité de l'information appropriés à votre organisation."; 
            itemCompliance.appendChild(itemComplianceImageContainer);
            itemCompliance.appendChild(itemComplianceDesc);
        itemContainer.appendChild(itemCompliance);
            const itemChecklist = document.createElement('div');
                itemChecklist.classList = 'center_item';
                const itemChecklistImageContainer = document.createElement('div');
                    itemChecklistImageContainer.classList = 'image';
                    const iconChecklistImage = new Image();
                        iconChecklistImage.src = icon_checklist;
                        iconChecklistImage.alt = "Checklist Icon";
                        iconChecklistImage.classList = "logo";
            itemChecklistImageContainer.appendChild(iconChecklistImage);
                const itemChecklistDesc = document.createElement('div');
                    itemChecklistDesc.classList = 'subtext';
                    itemChecklistDesc.innerHTML = "En fonction de vos objectifs, des mesures que vous avez déjà mises en place et de votre capacité opérationnelle, Kanply créera un plan d'action sur mesure, qu'il ajustera en continu."; 
            itemChecklist.appendChild(itemChecklistImageContainer);
            itemChecklist.appendChild(itemChecklistDesc);
        itemContainer.appendChild(itemChecklist);
            const itemCalendar = document.createElement('div');
                itemCalendar.classList = 'center_item';
                const itemCalendarImageContainer = document.createElement('div');
                    itemCalendarImageContainer.classList = 'image';
                    const iconCalendarImage = new Image();
                        iconCalendarImage.src = icon_event;
                        iconCalendarImage.alt = "Event Icon";
                        iconCalendarImage.classList = "logo";
            itemCalendarImageContainer.appendChild(iconCalendarImage);
                const itemCalendarDesc = document.createElement('div');
                    itemCalendarDesc.classList = 'subtext';
                    itemCalendarDesc.innerHTML = "Le calendrier de livraison des tâches sera géré par Kanply de façon à respecter vos objectifs et vos obligations."; 
            itemCalendar.appendChild(itemCalendarImageContainer);
            itemCalendar.appendChild(itemCalendarDesc);
        itemContainer.appendChild(itemCalendar);
            const itemColaboration = document.createElement('div');
                itemColaboration.classList = 'center_item';
                const itemColaborationImageContainer = document.createElement('div');
                    itemColaborationImageContainer.classList = 'image';
                    const iconColaborationImage = new Image();
                        iconColaborationImage.src = icon_team;
                        iconColaborationImage.alt = "Team Icon";
                        iconColaborationImage.classList = "logo";
            itemColaborationImageContainer.appendChild(iconColaborationImage);
                const itemColaborationDesc = document.createElement('div');
                    itemColaborationDesc.classList = 'subtext';
                    itemColaborationDesc.innerHTML = "Kanply assignera les tâches à l'intérieur de votre organisation ou à l'externe.  En plus de coordonner les efforts et de faire les suivis, il offrira le support et la formation requises à la réalisation des tâches."; 
            itemColaboration.appendChild(itemColaborationImageContainer);
            itemColaboration.appendChild(itemColaborationDesc);
        itemContainer.appendChild(itemColaboration);
    center.appendChild(itemContainer);
    return center.outerHTML;
}

export default generateAProposContent;